### PR TITLE
Fix sitemap.xml.gz in master (issue #209)

### PR DESCRIPTION
**Pull request by djowett**
(This is based on the similar PR #234 for 2.x branch)

First adding tests to check our tests show things up

### CODE REVIEW

**Comment by djowett** [comment]
This is good in my book - I don't expect Jenkins 5.0 to pass until we merge https://github.com/plone/plone.app.layout/pull/108.  
Don't know what the status would be of Jenkins 5.1 test - the parallel PR to merge is https://github.com/plone/plone.app.layout/pull/107, but it didn't look like PAM tests were passing in Plone 5.1 anyway. Any thoughts?

@jensens @Rudd-O

**Comment by djowett** [comment]
Thanks @mauritsvanrees for release of p.a.layout. Following up your [comment](https://github.com/plone/plone.app.layout/pull/108#issuecomment-269515473), is PAM expected to work in Plone 5.0, but not 5.1 then?

**Comment by mauritsvanrees** [comment]
Huh? No, plone.app.multilingual is expected to work fine on 5.1 too.

**Comment by djowett** [comment]
@mauritsvanrees thanks - my misunderstanding I think!

**Comment by djowett** [comment]
Rebased this after successful tests. Assuming this still passes can we get this merged ?

@Rudd-O can you test this works for you?

**Comment by Rudd-O** [comment]
I would have to check.  You should proceed without my input.

**Pull request merged**
