### PR TITLE
Add translation permission to Site Administrator role

### PR DESCRIPTION
**Pull request by davisagli**

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
This would require an upgrade step, right?

**Comment by davisagli** [comment]
@erral I could see the argument either way on the upgrade step. If someone customized the roles for this permission in an existing site, maybe we should not overwrite that.

**Comment by erral** [comment]
Then we should, at least, document in the README or CHANGELOG this change and document how to apply the change for existing sites. Something like "an optional upgrade step to run" or...

**Comment by davisagli** [comment]
@erral I updated the changelog

**Review by erral — APPROVED** [review]

**Pull request merged**
