### PR TITLE
force view_methods to be a tuple on setup and uninstall

### LINKED ISSUE #337: TypeError enabling languages in controlpanel
**Versions:**
Plone 5.1.5 (5115)
Zope 2.13.27
Python 2.7.15rc1
plone.app.multilingual 5.2.3

**Traceback:**
ERROR Zope.SiteErrorLog 1554797967.150.142960092785 http://localhost:8092/Plone/@@language-controlpanel
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 47, in update
  Module plone.z3cform.fieldsets.extensible, line 65, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 22, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.multilingual.browser.controlpanel, line 57, in handleSave
  Module plone.app.multilingual.browser.setup, line 83, in setupSite
  Module plone.app.multilingual.browser.setup, line 269, in setupLanguageSwitcher
TypeError: can only concatenate list (not "tuple") to list

**Steps to reproduce:**
- Installed plone.app.multilingual 5.2.3
- go to @@language-controlpanel
- add new language to available languages in the selection widget
- press save

**Other information:**
- Work around for me: Added the new available languages directly in portal_registry
- the problem in line 269 seems to be that site.view_methods is a list and the code tries to add a tuple (('language-switcher', )) to it < but i am not exactly sure what this code should do at this point
- on other Plone Sites (some in production already, but version 5.1.2) this problem doesn't persist

### PR DESCRIPTION
**Pull request by erral**
this fixes #337

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@erral Why is this closed but unmerged? It looks like a valid fix.

**Comment by erral** [comment]
I don't recall it I'm sorry... I think that I pinged the author of the issue to review the changes but nobody answered and I finally forgot about it... :smiley:

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
