### PR TITLE
Implement pat contentbrowser

### PR DESCRIPTION
**Pull request by 1letter**

### CODE REVIEW

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Comment by 1letter** [comment]
the test will fail until plone.app.z3cform > 4.6 is not in in https://dist.plone.org/release/6.1-dev/constraints.txt

**Comment by 1letter** [comment]
this changes are requires a new release plone.app.multilingual 8.2.x for Plone 6.1.

**Comment by petschki** [comment]
OK, so there should be a new `8.1.x` release and afterwards an `8.1.x` maintenance branch, so that we can merge this into `master` then. I'd say #468 also targets the new `8.2.x` version then ... what do you think @erral ?

**Comment by erral** [comment]
Yes, I agree. Both PRs should go to a new .x version

**Comment by petschki** [comment]
Note: I saw that Plone 6.0 is already pined to `7.x` so `8.1.x` is already Plone 6.1 only. But for semantic versioning reasons `8.2.0` makes sense of course.

**Pull request merged**
