### PR TITLE
Rename media to assets

### PR DESCRIPTION
**Pull request by agitator**
closes https://github.com/plone/plone.app.multilingual/issues/280

### CODE REVIEW

**Comment by datakurre** [comment]
Changing the default name of media folder into "assets" is ok for me.

@jensens @thet Any objections?

**Comment by erral** [comment]
Will this break existing sites that upgrade to the new version of p.a.m?

I see that the subscriber that takes care of the LIF doesn't make any assumption on the id of the folder, but just to be sure...

**Comment by erral** [comment]
Moreover, I think that we should i18nize the tilte "Assets" for the folder. While "Media" could be understood in all languages, "Assets" is not and I think it requires a proper msgid in the po files.

**Comment by datakurre** [comment]
@erral Thanks for noticing that assets is not as "universal" as "media". I try to convince @agitator to i18nize it.

And correct, id can be anything and the default id and title only affect the new folders. LIF folders can also be renamed manually, but it requires making them implicitly addable at first.

**Comment by datakurre** [comment]
FYI. I did not touch translate menu here. After this has been approved, I submit a comprehensive  refactoring for the translate menu contents.

**Comment by datakurre** [comment]
I assume this is ok now.

**Pull request merged**
