### PR TITLE
Keep assets_folder_id lang neutral for default setup

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by agitator** [comment]
True... I'd like the idea to make it a constant `ASSETS_FOLDER_ID` which could be overridden in an integration package. 
@datakurre what do you think? https://github.com/plone/plone.app.multilingual/commit/0be09c3897cfbb7b4d6c3fa57e5d3febbcbdb72e#commitcomment-23501993 in case you missed that

**Comment by datakurre** [comment]
I don't understand the problem. Both name and id had own translation strings, so any language can choose whether to have the id localised or not. IMHO, customising with localisation has better discoverability than module globals.

But if this is changed, make sure to also update docs.

**Comment by mauritsvanrees** [comment]
There was a worry by some that maybe something would not work if the id of this folder was not `assets` in all languages. I don't know if this is a valid point: I have not used the assets folder. Nor have I used multilingual much.

I don't mind if the id is translated. I only jumped in because the tests started failing after someone innocently added a translation in the Spanish po file.

**Comment by datakurre** [comment]
@mauritsvanrees Thanks for fixing the tests.

IMO the issue here was accidental push directly to master and not the id being localizable. Everything in PAM relies on UUIDs and TGs (translation groups). Ids do not matter.

In my original LIF impl I did not have them by default, but added them manually when required and translated them into every language using PAM translation menu :)

**Comment by mauritsvanrees** [comment]
Then it seems fine like it is now, and this pull request is not needed. Closing.

**Comment by erral** [comment]
The point is that I added the translation in the spanish file, but didn't realize that there was a test in p.a.multilingual that used `portal.es.assets` (or whichever way to access the folder). I should have checked that and fix the test.

**Comment by datakurre** [comment]
Yes, there was nothing wrong in translating it. Thanks!

**Pull request closed without merging**
