### PR TITLE
2.x tests want fixing

### PR DESCRIPTION
**Pull request by djowett**
WIP 
this works locally.

Current issue on travis is that contenttree doesn't show the English document...
either it isn't there
or the tree was collapsed by the click

https://s3.amazonaws.com/plone-app-multilingual/plone/plone.app.multilingual/618/618.1/robot/test_add_translation/Scenario_As_an_editor_I_can_add_new_translation/log.html 

Nice we can see the robot test output online

### CODE REVIEW

**Comment by djowett** [comment]
Not working yet.

But I did spot something - if you look closely at the screenshot below (note the buttons), then I think that you see that plone.formwidget.contenttree is in "graceful fallback" mode ?!  Maybe that is the cause of the problem?  @mauritsvanrees sorry to bug you again, but I saw you worked a bit on that.  Any ideas?

https://s3.amazonaws.com/plone-app-multilingual/plone/plone.app.multilingual/626/626.1/robot/test_add_translation/Scenario_As_an_editor_I_can_add_new_translation/log.html

**Comment by djowett** [comment]
@frisi ! 
Can I just get your opinion here?   I noticed [your comment in this archetypes.multilingual issue](https://github.com/plone/archetypes.multilingual/issues/13#issuecomment-101440831) (possibly fixes, but as yet unmerged):
> ... however, the widget in the dialog for linking existing objects as translations (@@add_translations) still does not work (contenttreewidget does not find items of the specified language).
do i need plone.app.widgets to make this work properly?

This seems pretty close to the test failure we have on 2.x branch on Travis here (I'm not seeing it locally).
Any comments?
Also  @keul, any thoughts? I see you provided a fix for the above issue.

Sorry if I'm off target & this is unrelated!

**Comment by keul** [comment]
@djowett sorry no idea about your robottest issue, I provided the fix just because Archetypes + p.a.multilingual was not working (and still they are, as the PR was never merged).

**Comment by djowett** [comment]
Replaced by #204

**Pull request closed without merging**
