### PR TITLE
[2.x] Fix and tidy tests, fix dependencies

### PR DESCRIPTION
**Pull request by djowett**
This replaces #198 as that PR has too many "trial & error commits", and this one makes clear where the issue is. (A rebase will come later)

### CODE REVIEW

**Comment by djowett** [comment]
@bsuttor it seems that the changes in https://github.com/plone/archetypes.multilingual/pull/17 caused the failure of PAM 2.x tests.  Any idea why?

**Comment by bsuttor** [comment]
I'm sorry but I have no idea,
We think about not using archetypes.multilingual anymore and migrate our multilingual sites with plone.app.contenttypes.

**Comment by djowett** [comment]
@bsuttor thanks for the reply. I'm using PAC too, but obviously it would be good to have the PAM 2.x tests passing.  Perhaps the changes in archetypes.multilingual shouldn't assume it is installed? i.e. Add a condition in the ZCML?

**Comment by bsuttor** [comment]
I don't understand, which zcml file you would add condition ?

We have to find why tests for plone.app.multilingual are impacted by archetypes.multilingual package ? It should not. We have to find a way to test plone.app.multilingual without archetypes.multilingual. 
Tests for archetypes.multilingual  should by in archetypes.multilingual  package ;)

**Comment by djowett** [comment]
@bsuttor sorry not to get back sooner.  I was talking about `archetypes/multilingual/configure.zcml` but probably that won't work.

I think there's 2 issues here:

1. p.a.m 2.x checks out archetypes.multilingual package for it's tests. I don't think it should.  Perhaps @jensens or @saily have an opinion on whether to keep that?
2. More seriously, the [recent changes in archetypes.multilingual 2.x](https://github.com/plone/archetypes.multilingual/pull/17) are making the p.a.m tests fail.  I'm guessing that this is because archetypes.multilingual overrides dexterity functionality to make archetypes work, and it does this even when it's not installed as an addon, so *all* the p.a.m tests are picking up even if they are testing dexterity stuff .  I guess  a browserlayer would be nice here, but probably that wouldn't work, so maybe there's something similar which would work in this case?

**Comment by djowett** [comment]
Rebased, I expect this to fail because of changes in 2.x branch of archetypes.multilingual

For my next trick, I hope to make them pass by checking out 2.0 release of archetypes.multilingual

**Comment by djowett** [comment]
Hmm, sort of....

@bsuttor you said earlier:
> I don't understand, which zcml file you would add condition ?

I think adding a Browser layer as done [in this commit in master](https://github.com/plone/archetypes.multilingual/commit/e67a2921496211fd2aa5effc48e3fe370da6e40c) combined with taking the advice from [this SO answer on using browserlayers in subscribers](http://stackoverflow.com/questions/29919893/how-to-declare-a-subscriber-that-will-be-enable-for-only-one-plone-site/29920079#29920079) may sort this out.  What do you think?

**Comment by bsuttor** [comment]
I think it's a good idea to add a browserlayer for archetypes.multilingual. 
However browserlayer should also be in uninstall profile ;-) like this:

    <layers>
      <layer
          name="archetypes.multilingual"
          interface="archetypes.multilingual.interfaces.IArchetypesMultilingualInstalled"
          remove="True"
    </layers>

**Comment by djowett** [comment]
Ok, I can have a go to do it, but I'm not using archetypes.multilingual 
at the mo, so would you be able to check I haven't broken it?



On 08/01/16 08:43, Benoît Suttor wrote:
>
> I think it's a good idea to add a browserlayer for 
> archetypes.multilingual.
> However browserlayer should also be in uninstall profile ;-) like this:
>
> |<layers> <layer name="archetypes.multilingual" 
> interface="archetypes.multilingual.interfaces.IArchetypesMultilingualInstalled" 
> remove="True" </layers> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/pull/204#issuecomment-169935745>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by djowett** [comment]
Well done to @bsuttor for fixing the 2.x tests in #208.  

That changes the objective of this PR - we no longer have to fix tests, but issues/fixes uncovered in the process should still get merged IMO - not least the pinning to archetypes.multilingual 2.x branch.

rebase on 2.x coming soon

**Comment by jensens** [comment]
tests are passing, is this one ready for merge?

**Comment by djowett** [comment]
@jensens it is IMO, would appreciate a quick sanity check on the changes

**Comment by djowett** [comment]
@jensens I'm seeing random test failures locally, so this has gone back to WIP for now.

**Comment by djowett** [comment]
This image shows how the add translation test sometimes fails.

add_translation test fails

My best guess at interpreting that is:

1. `Click Element  xpath=(//span[contains(., 'English')])`  is not specific enough & collapses the English folder rather than selecting the document.
2. `Wait until page contains  An English Document` still sees the text because the collapse is a relatively slow animation  (shown midway complete by the above image)
3. but `Click link  xpath=//*[contains(text(), 'An English Document')]/parent::a` *doesn't* see "An English Document" because the animation is complete

**Comment by jensens** [comment]
Idea: As a workaround you can try a"Sleep  500ms" before the wait.

**Comment by djowett** [comment]
This test looks REALLY wrong
https://s3.amazonaws.com/plone-app-multilingual/plone/plone.app.multilingual/720/720.1/robot_log.html#s1-s1
- Catalan document in English Root Folder, instead of English Document
- how did a `Click Link xpath=//*[contains(text(), 'An English Document')]/parent::a` succeed straight after this screenshot?
https://s3.amazonaws.com/plone-app-multilingual/plone/plone.app.multilingual/720/720.1/robot_log.html#s1-s1-t1-k6-k10

**Comment by jensens** [comment]
omg, I have no idea. Looks like the test does not match the code it supposed to test.

**Comment by datakurre** [comment]
I'm trying to check this soon.

**Comment by datakurre** [comment]
@djowett The first screenshot looks weird indeed. I managed to reproduce it by selecting the Catalont document itself as its English translation. I rebuild the Travis build a few times and it didn't flicker anymore for me. So, this probably was a timing issue after all. I think that for "page contains" keywords it's enough for an element to be in DOM, but not necessary visible. (And that's solves your second question. The screenshot was captured before "An English Document" become visible.) Adding explicit check for visibility seem to fix the test.

As a side note, the most basic tips for debugging an individual test are keywords ``Set selenium speed  0.5" and ``Debug``.

**Comment by datakurre** [comment]
Or not. Still flickers :(

**Comment by djowett** [comment]
@jensens thanks to help from @datakurre these tests look stable now.

I'm happy for this to be merged if you are.

**Comment by jensens** [comment]
great!

**Pull request merged**
