### PR TITLE
Backport  fix to disconnect translation for 7.x

### PR DESCRIPTION
**Pull request by krissik**
See #449

### CODE REVIEW

**Comment by krissik** [comment]
If I run zprettier locally I see that it will add the additional ';' again (which caused the bug)

```
diff --git a/src/plone/app/multilingual/browser/templates/modify_translations.pt b/src/plone/app/multilingual/browser/templates/modify_translations.pt
index eb6576b..0769e38 100644
--- a/src/plone/app/multilingual/browser/templates/modify_translations.pt
+++ b/src/plone/app/multilingual/browser/templates/modify_translations.pt
@@ -74,7 +74,7 @@
                      href="#"
                      title="Disconnect translation"
                      tal:attributes="
-                       href python:context.absolute_url() + '/disconnect_translation?came_from=' + context.UID() + '&language=' + lang;
+                       href python:context.absolute_url() + '/disconnect_translation?came_from=' + context.UID() + '&language=' + lang;;
                      "
                      i18n:attributes="title disconnect_translation"
                   >
```

How can I exclude modify_translations.pt? I have tried

```
[pre_commit]
zpretty_extra_lines = """
        extend-exclude: "modify_translations\.pt"
"""
```
at .meta.toml and run plone-meta again. But it is not working.

**Comment by davisagli** [comment]
@krissik Try getting rid of both semicolons. I don't think a semicolon is needed when there is only one attribute, and it may be that zpretty is not handling that case correctly.

**Comment by krissik** [comment]
@jenkins-plone-org please run jobs

**Comment by krissik** [comment]
> @krissik Try getting rid of both semicolons. I don't think a semicolon is needed when there is only one attribute, and it may be that zpretty is not handling that case correctly.

There is an issue with zpretty https://github.com/collective/zpretty/issues/130
I have encoded `&` - now zpretty is happy.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
