### PR TITLE
Really don't show the Google Translate button when no API key set

### LINKED ISSUE #184: Google Translate button is shown even when no translation key in settings
this seems to be because the check doesn't test for None.  The test in BabelUtils looks correct, those in add.py & edit.py are not.

### PR DESCRIPTION
**Pull request by djowett**
fixes #184 on master

Sibling to PR's #185 for 1.x and #199 for 2.x

Also remove unused gtenabled() methods in add.py & edit.py

### CODE REVIEW

**Comment by jensens** [comment]
@djowett may you rebase, then this one is ready for merge

**Comment by djowett** [comment]
@jensens - rebase done, ready to go 

Are you OK with me changing the labels btw, or would you prefer to do it yourself? (for at least certain categories?)

**Comment by djowett** [comment]
@jensens this needed another rebase (after  3.0.15 release), but it's ready now.

**Comment by jensens** [comment]
it still merges - the changes do not interfere as it seems.

**Pull request merged**
