### PR TITLE
fixed babel_view lookup with more specific interface

### PR DESCRIPTION
**Pull request by jihaisse**
This will fix https://github.com/plone/plone.app.multilingual/issues/180

### CODE REVIEW

**Comment by jensens** [comment]
@jihaisse before we can accept your contribution please sign the contributor agreement, see https://plone.org/foundation/contributors-agreement

**Comment by jihaisse** [comment]
@jensens I've signed it, and I am now member of the Plone Foundation ;)
You can accept the merge if you want to.

**Comment by jensens** [comment]
welcome!

**Comment by jihaisse** [comment]
Yeah.
Thanks

Le mer. 2 mars 2016 10:20, Jens W. Klein <notifications@github.com> a
écrit :

**Pull request merged**
