### PR TITLE
Fix sitemap.xml.gz in 2.x (issue #209)

### PR DESCRIPTION
**Pull request by djowett**
See https://github.com/plone/plone.app.layout/issues/91 and https://github.com/plone/plone.app.layout/pull/92
Also see #209 

cc @erral

### CODE REVIEW

**Comment by jensens** [comment]
@djowett this and the opther PR are a complex series - but as far as I can see well thought and tested and from what I understand it looks good to me.

 I'd ask you and @erral as the two persons with insight to the topic to merge them yourself if you both decide its ready.

**Comment by djowett** [comment]
@jens  thanks for this  - I'm sure we can do.

@erral - sorry for my silence on this, other things got in the way. I 
will aim to get back to this the end of next week.

On 10/06/16 08:21, Jens W. Klein wrote:
>
> @djowett <https://github.com/djowett> this and the opther PR are a 
> complex series - but as far as I can see well thought and tested and 
> from what I understand it looks good to me.
>
> I'd ask you and @erral <https://github.com/erral> as the two persons 
> with insight to the topic to merge them yourself if you both decide 
> its ready.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/pull/234#issuecomment-225111261>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABZuRXk7UZKPPodKZZISHteJwHL11sJdks5qKRCUgaJpZM4IrpHi>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by djowett** [comment]
Ok, this is good to go IMO.  Review and merge anyone?

@jensens @erral @Rudd-O

**Comment by djowett** [comment]
@plone/release-team can we make a release on this branch too?

**Pull request merged**
