### PR TITLE
Really don't show Translate button when no API key.

### LINKED ISSUE #184: Google Translate button is shown even when no translation key in settings
this seems to be because the check doesn't test for None.  The test in BabelUtils looks correct, those in add.py & edit.py are not.

### PR DESCRIPTION
**Pull request by djowett**
Also remove unused gtenabled() methods in add.py & edit.py - however I'm not sure whether you want to be deprecating things in utils.py - Any comments @thet?

rename hidden field `gtanslate_service` to `gtranslate_service_available` (not really nec, but the spelling was bugging me anyway).

### CODE REVIEW

**Comment by bloodbare** [comment]
I'm ok to merge it

**Comment by djowett** [comment]
Thanks for the vote... Tests do pass locally - not sure why the process seems to have died on Travis.  Note this is for 1.x branch (I've not got my current site set up to work on master yet)

By the way the functions getGroup getTranslatedLanguages getPortal & objToTranslate in BabelUtils seem to also be unused.

**Comment by jensens** [comment]
travis shows an assertion error. since youre change intentionally hides a button, you may double check if this button in the test should be affected or not - and change code or test in order to fix it.
https://travis-ci.org/plone/plone.app.multilingual/jobs/81416011#L2348

**Comment by djowett** [comment]
@jensens the travis is not caused by this change - it seems to have originated at #165 on the 1.x branch.  
The major issue there is that the "allowed failure" test [shown here](https://travis-ci.org/plone/plone.app.multilingual/builds/66072415) seems to be causing the failure of the other travis tests.

@mauritsvanrees @do3cc

**Comment by djowett** [comment]
Hey, (it seems that my personal WPOD was yesterday)... I've got a bit further with fixing the tests on Travis, but I could do with some help now if anyone wants to step up!  4.3 is actually working OK on travis-ci/push, and the error on PR seems to be a temporary network error.  The issues on 4.2 need resolving though...

Stuff I fixed in the tests so far:
* pin archetypes.multilingual < 2.0 (any more seems to expect Plone5)
* only runs p.a.m tests in Travis (not multilingualbehavior etc) - the same is done in 2.x & master branches
* fix the tar issue - basically it seems `python bootstrap` was putting setuptools etc in buildout-cache/eggs/ and then tar xv doesn't handle overwriting files
*  reset travis.cfg to extend test-plone-4.x.cfg so that it can be replaced by the sed command in .travis.yml

Any takers to help?

**Comment by djowett** [comment]
I should say that tests do pass locally (my 4.3 install)

**Comment by mauritsvanrees** [comment]
The tests were failing for me locally with Python 2.7 and Plone 4.2.  Then I added lower version pins for a few robot framework packages in test-plone-4.2.cfg and then all was fine locally. But Travis still fails...

And on failure we are trying to upload the artifacts to an S3 bucket, but this fails with "hostname does not match the server certificate", so that is not helpful either.... https://travis-ci.org/plone/plone.app.multilingual/jobs/92376064

Anyone else want to have a go?

Personally, I don't mind dropping 4.2 (and 4.1) support, but it is always disappointing when you have to do that not because of an actual incompatibility, but only because a test is failing that you can't reproduce locally...

**Comment by djowett** [comment]
@mauritsvanrees thanks for stepping in!  I don't understand why changing selenium pins works, but not to worry.

The last error MoveTargetOutOfBoundsException rang a bell from collective.cover - I'm out of time now, but there are 2 ideas of how that exception might be fixed in this [c.cover issue](https://github.com/collective/collective.cover/pull/451). TLDR; either 
a) scroll the required element into view OR [increase screen resolution](https://groups.google.com/forum/#!topic/travis-ci/h0-4OnPViFk)  
b) make sure that (for example) the correct tab in a popup is selected so the element is REALLY visible on screen.  (Also make sure the xpath / css in question is specific enough to only select ONE element)

**Comment by djowett** [comment]
@mauritsvanrees increasing screen size gets us back to the [error on portal-language-selector](https://travis-ci.org/plone/plone.app.multilingual/jobs/92694952#L1674) that was [seen earlier](https://travis-ci.org/plone/plone.app.multilingual/jobs/92222397#L1504),
I'm thinking that pinning back selenium & friends may not have helped - though the screen size thing seems to have compensated for that, but we could probably roll back both commits.

I can reproduce the error on portal-language-selector locally and that gives me the following screenshot  - it seems like the earlier `Click Element  css=.contentTreeAdd` isn't firing for some reason and therefore the requester/popup stays open.... I will take a look later, unless anyone has immediate understanding of why that might be
selenium-screenshot-1

**Comment by djowett** [comment]
Ok, I discovered the problem (as shown by the passing test above) - but this is still WIP.

So basically, the problem is caused by [this commit](https://github.com/plone/plone.formwidget.autocomplete/commit/a3c070596c8fa9c51874e772c5203e06d587aa91) in plone.formwidget.autocomplete which is included in versions 1.2.5 upwards.  The issue is that it uses [jquery.prop()](http://api.jquery.com/prop/) which depends on JQuery 1.6, and Plone 4.2 only ships with JQuery 1.4.  @mauritsvanrees actually raised this on the commit itself, but that was ignored.
Unfortunately  Plone 4.2.6 & 4.2.7 pin plone.formwidget.autocomplete 1.2.5.

So in actual fact my pin in `test-plone-4.2.cfg` should be removed, as the tests for 4.2 *should* fail here.

The question is how to properly fix this here? Any ideas anyone?

**Comment by djowett** [comment]
Rebased and squashed some commits to tidy up the commit history .... that's uncharted territory for me, so hopefully it's a-ok.

**Comment by djowett** [comment]
All is good - thanks to @mauritsvanrees for taking time to talk me through rebase.  Anyone want to merge this?

**Comment by mauritsvanrees** [comment]
Merged. Thanks a lot for the change and for taking so much time to get Travis working again!

**Comment by djowett** [comment]
Great! Thanks for reviewing!

**Pull request merged**
