### PR TITLE
remove CMFDefault dependency

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by gforcada** [comment]
Running tests on http://jenkins.plone.org/job/pull-request/165

**Comment by jensens** [comment]
5 failures

**Comment by tomgross** [comment]
Are you sure these failures are linked to my changes? All tests of CMFPlone and plone.app.theming on my machine.

**Comment by tomgross** [comment]
Travis is testing against Plone 4.3 which can't work for the master branch

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request/175/

**Comment by tisto** [comment]
Pull request test passed. Merged.

**Pull request merged**
