### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
@jensens this one is meant for the `core addon`? so `plone.api` is fine and depending on `CMFPlone` as well, right?

Otherwise we have to adjust the dependencies 🍀

### CODE REVIEW

**Comment by jensens** [comment]
Can we wait until core-addon branch is merged and rebase this one?

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
I am always for early release, but I understand if this is too much effort.

**Comment by jensens** [comment]
@mauritsvanrees I think we can merge this now. What do you think?

**Comment by gforcada** [comment]
@jensens we could remove the `circular` GHA to get this green, but is there any plan to get rid of this circular dependency? 🤔 

Ideas and plans in the tracking issue: https://github.com/plone/Products.CMFPlone/issues/3859

**Comment by mauritsvanrees** [comment]
The circular check does not work yet.
See https://github.com/plone/Products.CMFPlone/issues/3859#issuecomment-1768601882 and further.  (I thought I was adding those in this PR.)

**Comment by mauritsvanrees** [comment]
Now the `test`, `coverage`, and `circular` jobs all fail for the same reason, an installation conflict because we want to install a dev version of p.a.multilingual and we have a version pin for this in the constraint.

I am trying out mxdev locally, analogous to how we already have it in `plone.namedfile`.

**Comment by mauritsvanrees** [comment]
It is green!  Long live mxdev!  Once we merge this, I can make a release, update the version on 6.1-dev, and then other packages should no longer have this problem.

So now we have in `tox.ini` roughly:

```
[testenv:test]
skip_install = true
deps =
    mxdev
    zope.testrunner
    -c https://dist.plone.org/release/6.1-dev/constraints.txt
commands_pre =
    mxdev -c mx.ini
    pip install -rrequirements-mxdev.txt
commands =
# We have robot tests, so we have this line extra:
    rfbrowser init
    zope-testrunner --all --test-path={toxinidir}/src -s plone.app.multilingual {posargs}
```

and `mx.ini`:

```
[settings]
ignores = plone.app.multilingual
main-package = -e .[test]
```

and `mxdev` by default reads `requirements.txt`:

```
-c https://dist.plone.org/release/6.1-dev/constraints.txt
```

In `plone.app.z3cform` we have the same problem.  There the master branch is also for Plone 6.1 only, to we extend `6.1-dev`.  Here also `tox -e test` gives an unhelpful error message:

```
The conflict is caused by:
    plone-app-testing 7.0.1 depends on Products.CMFPlone
    The user requested (constraint) products-cmfplone==6.1.0a1.dev0
```

So there we need mxdev as well.  I don't know why is this not (yet) a problem on packages where we test with 6.0.  Using mxdev should be fine everywhere I think.

**Review by jensens — APPROVED** [review]

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
