### PR TITLE
relocation fix for 2.0

### PR DESCRIPTION
**Pull request by pbauer**
@agitator is the ready to merge?

### CODE REVIEW

**Comment by jensens** [comment]
- not ready: changelog entry missing.
- tests here: http://jenkins.plone.org/job/pull-request-5.0/392/
- is this a backport from master or do we need this on master as well?

**Comment by pbauer** [comment]
@agitator ping

**Comment by agitator** [comment]
since this migration should be run before moving to plone 5 and p.a.m 2.x is only supported by for plone 4. it shouldn't be part of p.a.m 3.x - other opinions?

**Comment by agitator** [comment]
test failures on 5 don't seem related to this change

**Pull request merged**
