### PR TITLE
take RichTextBehavior fields into account when using google translate

### LINKED ISSUE #464: RichText field contents are ignored when trying to use Google Translate service
The existing JavaScript code relies on old Plone markup (it looks for `mce-editable` class which no longer exists) which makes it ignore the current rich text fields.

### PR DESCRIPTION
**Pull request by erral**
Fixes #464 

The old code had references to archetypes fields, not needed any more, and ignored current RichText fields.

This implementation works *only* with fields coming from the RichTextBehavior. It can't work with standard schema based RichText fields, because they have no marker in the HTML to signal that they are rich text fields.

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
I don't know if you can help me here @1letter and @petschki 

I need some review on this to have the confirmation that this is right.

The point is that we have some JS code to get the value of a field and send it through a browser view to a translation service (this is already implemented in p.a.multilingual yay!), but it does not work with the current richtext fields although I do these changes.

**Comment by petschki** [comment]
I'll take a look today. I saw some issues notably that my translation page is getting longer and longer every second 😉  ... I'll come up with some improvements.

**Comment by erral** [comment]
> I'll take a look today. I saw some issues notably that my translation page is getting longer and longer every second 😉 ... I'll come up with some improvements.

Use the latest code in `master` we merged some changes to get the context correctly some days ago.

**Comment by petschki** [comment]
I've rewritten the babel helper in order to meet the current classic-ui standards. (still some `$.ajax` calls in there, but thats ok) ... the vertical repositioning is now "just" setting the heights of the fields equally instead of calculating each height/padding individually. I think it looks much better this way.  Also there's some code cleanup for the visibilities and I use the `pat-autotoc` "clicked" event to trigger the visible fields on the page ...

unfortunately setting the content of tinymce to the translated text is a bit flaky ... need to check whats the problem there. Sometimes I see updated word count but no content 🤔

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]

**Pull request merged**
