### PR TITLE
2.x fix 'is a translation' viewlet

### PR DESCRIPTION
**Pull request by djowett**
Fix for #202 on 2.x

### CODE REVIEW

**Comment by djowett** [comment]
@mauritsvanrees do you mind to have a quick look at this at some point?

It passes locally, but doesn't on Travis - I think this is because I am testing for a translation & the *.mo files are not available to Travis.  Do you think that is so?  Should I not test for a translation? or can we perhaps run a tool (i18ndude) on Travis to generate the *.mo files?

[This](https://travis-ci.org/plone/plone.app.multilingual/jobs/114227687#L1311) is the error:
     Robot.Test Translate Content                                                  
     ==================================
    Scenario: As an editor when I create a translation I see informati... | FAIL |

    Element 'css=.portalMessage.info' should have contained text 'Cette élément est sur le point d'être traduit en Français à partir de :' but its text was 'Info 
    This object is going to be a translation to Français from:
     English An English Document Català A Catalan Document
    If you want to create this object without being a translation press here'.

**Comment by mauritsvanrees** [comment]
I don't usually test translations, but it may make sense here.
In `.travis.yml` you can `pip install zest.pocompile` and then run the `pocompile` command. That will compile the .po files to .mo files.
See https://pypi.python.org/pypi/zest.pocompile

**Comment by djowett** [comment]
Thanks @mauritsvanrees  - that worked perfectly.

**Comment by djowett** [comment]
I believe that this is ready, but with so many files changed I'd appreciate a review.   I'm open to squashing some commits if it's thought appropriate.

**Comment by mauritsvanrees** [comment]
Looks good to me. Thanks for working on this!

**Comment by mauritsvanrees** [comment]
I have released 2.0.2 with this.
Thanks again!

**Pull request merged**
