### PR TITLE
sitemap changes and tests coming from plone.app.layout PR #92

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by erral** [comment]
See https://github.com/plone/plone.app.layout/pull/92 before merging.

**Comment by djowett** [comment]
@erral Ah, right I see your issue.

Then I *think* we should just add a pin in `plone.app.multilingual/test-plone-4.3.x.cfg` because we are not trying to *force* PAM 1.x users to take our fix, we are only checking it doesn't break things for them. 

But if you still think we should pin in setup.py, then I would do something like this here:

      requirements=[
        'setuptools',
        'five.grok',
        'plone.multilingual>=1.1',
        'z3c.relationfield',
        'plone.app.z3cform',
        'plone.app.registry',
        'plone.directives.form',
        'plone.formwidget.contenttree',
        'Products.PloneLanguageTool',
        'archetypes.multilingual < 2.0',  # required while archetypes is default in Plone
      ],

     # I left you this bit - cos I'm not sure how to do it (unless we can use plone.api?)
     plone_version = xxx.yyy
     if plone_version >= '4.3':   
         requirements.append('plone.app.layout > 2.3.14')

      ....
        install_requires=requirements,

**Comment by erral** [comment]
And how are we supposed to maintain compatibility with Plone 4.2 that uses p.a.layout 2.2.x ?

**Comment by djowett** [comment]
@erral you've got me thinking, but do we *really* need to fix in p.a.layout 2.2.x ? ....

We are fixing an issue which occurs when using plone.app.multilingual > 2.x and above.
The fix needs to be in plone.app.layout branches that are used by Plone versions that use PAM > 2.x.
So the big question is:
  Is PAM 2.x used by Plone 4.2 (or 4.1)?  Are you doing that?

theoretically speaking:
* We don't test PAM 2.x with [anything lower than 4.3](https://github.com/plone/plone.app.multilingual/blob/2.x/.travis.yml#L13)
* Plone 4.2 is restricted to 1.0 of plone.app.contenttypes, does that version work with PAM 2.x?
so it's a narrow case

I think unless you or someone we know *is* using this combination, then I'd rather just add a note in the Issue / PR that a backport may be required if someone is in that circumstance.  This is fun, but more than enough work :-)

**Comment by erral** [comment]
But my branch tests PAM 1.x which is available both for Plone 4.3.x and
Plone 4.2.x.

On Fri, Jun 3, 2016 at 2:31 PM, Daniel Jowett <notifications@github.com>
wrote:

> @erral <https://github.com/erral> you've got me thinking, but do we
> *really* need to fix in p.a.layout 2.2.x ? ....
>
> We are fixing an issue which occurs when using plone.app.multilingual >
> 2.x and above.
> The fix needs to be in plone.app.layout branches that are used by Plone
> versions that use PAM > 2.x.
> So the big question is:
> Is PAM 2.x used by Plone 4.2 (or 4.1)? Are you doing that?
>
> theoretically speaking:
>
>    - We don't test PAM 2.x with anything lower than 4.3
>    <https://github.com/plone/plone.app.multilingual/blob/2.x/.travis.yml#L13>
>    - Plone 4.2 is restricted to 1.0 of plone.app.contenttypes, does that
>    version work with PAM 2.x? so it's a narrow case
>
> I think unless you or someone we know *is* using this combination, then
> I'd rather just add a note in the Issue / PR that a backport may be
> required if someone is in that circumstance. This is fun, but more than
> enough work :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/plone/plone.app.multilingual/pull/235#issuecomment-223566312>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAx41ZZLdUEWcV1bpwOs-4EwAFOsp8-cks5qIB6JgaJpZM4ItUj4>
> .
>



-- 
Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80

**Comment by djowett** [comment]
I think I;m clear on this now....

But for PAM 1.x we only want to prove that it /doesn't make a 
difference/ to the sitemap
which plone.app.layout they take (2.3.15 or earlier).
So we provide a pin in the 4.3.x test
(add plone.app.layout = 2.3.15 in test-plone-4.3.x.cfg)
but /not/ in the 4.2.x test

What we don't need to (or want to) do is force////people to take our 
change when they are only using PAM 1.x, so we can remove the pin on 
plone.app.layout from setup.py

I think that should work....





On 03/06/16 16:42, Mikel Larreategi wrote:
> But my branch tests PAM 1.x which is available both for Plone 4.3.x and
> Plone 4.2.x.
>
> On Fri, Jun 3, 2016 at 2:31 PM, Daniel Jowett <notifications@github.com>
> wrote:
>
> > @erral <https://github.com/erral> you've got me thinking, but do we
> > *really* need to fix in p.a.layout 2.2.x ? ....
> >
> > We are fixing an issue which occurs when using plone.app.multilingual >
> > 2.x and above.
> > The fix needs to be in plone.app.layout branches that are used by Plone
> > versions that use PAM > 2.x.
> > So the big question is:
> > Is PAM 2.x used by Plone 4.2 (or 4.1)? Are you doing that?
> >
> > theoretically speaking:
> >
> > - We don't test PAM 2.x with anything lower than 4.3
> > 
> <https://github.com/plone/plone.app.multilingual/blob/2.x/.travis.yml#L13>
> > - Plone 4.2 is restricted to 1.0 of plone.app.contenttypes, does that
> > version work with PAM 2.x? so it's a narrow case
> >
> > I think unless you or someone we know *is* using this combination, then
> > I'd rather just add a note in the Issue / PR that a backport may be
> > required if someone is in that circumstance. This is fun, but more than
> > enough work :-)
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/plone/plone.app.multilingual/pull/235#issuecomment-223566312>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/AAx41ZZLdUEWcV1bpwOs-4EwAFOsp8-cks5qIB6JgaJpZM4ItUj4>
> > .
> >
>
>
>
> -- 
> Mikel Larreategi
> mlarreategi@codesyntax.com
>
> CodeSyntax
> Azitaingo Industrialdea 3 K
> E-20600 Eibar
> Tel: (+34) 943 82 17 80
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/plone/plone.app.multilingual/pull/235#issuecomment-223614651>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABZuRSOkyktUiNPHN2ou12HfzMKZpvXwks5qIEt9gaJpZM4ItUj4>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by djowett** [comment]
Hi @erral, I've been taking another look at this & I'm coming to the conclusion that the sitemap is already broken on the PAM 1.x / Plone 4.2 combination.  Do you agree?

https://travis-ci.org/plone/plone.app.multilingual/jobs/135087425 shows links not appearing in the sitemap, and I've tested this manually on a fresh buildout - it seems that documents in some languages (the non default ones?) get missed off the sitemaps....

It's surprising because I thought the sitemap is working for the combination of PAM 1.x & Plone 4.3 - but I better double check that too!

cc @Rudd-O

**Comment by erral** [comment]
I need to refresh this :)

The sitemap works for me on:

- Plone 4.3 - PAM 1.x branch - p.a.layout 2.3.x_issue_91 branch

The sitemap works for me partially on:

- Plone 4.2 - PAM 1.2.2 - p.a.layout 2.2.10.

With partially I mean that it works for the language folders, but it doesn't work for the whole site's sitemap, it only returns the contents of one language; presumably because the "language: 'all'" "hack" is missing.

**Comment by erral** [comment]
I think we should ignore the whole Plone 4.2 thing, just mark the next PAM 1.x release for Plone 4.3.x only, and let it go.

**Comment by djowett** [comment]
@erral Thanks - in the end I just skipped these new sitemap tests for Plone 4.2 - if someone wants to backport the fix into p.a.layout 2.2.x later then these tests would I guess (as you did above) be fixed.  I just don't want to get any further into changing versions I'm not using at this time.

The fixed PR is #236.  But before we merge it, I should get someone to merge and release my fix in p.a.layout

**Comment by djowett** [comment]
@erral I'm closing this as it is superceded by #236 - thanks for starting things off!

**Pull request closed without merging**
